// Sample business data for testing different niches
// These are pre-filled examples users can load to quickly test the website builder

import { IntakeFormData, DEFAULT_COLORS } from './types';

export interface SampleBusiness {
    id: string;
    name: string;
    description: string;
    icon: string;
    data: IntakeFormData;
}

export const SAMPLE_BUSINESSES: SampleBusiness[] = [
    {
        id: 'water-damage-gilbert',
        name: 'Water Damage Gilbert, AZ',
        description: 'Real test business - water damage restoration in Gilbert',
        icon: '💧',
        data: {
            businessName: 'Water Damage Gilbert, AZ',
            industry: 'restoration',
            customIndustry: '',
            services: [
                { name: 'Water Damage Restoration', description: '24/7 emergency water extraction and drying for flooded homes and businesses in Gilbert, AZ. We respond within 60 minutes to minimize damage and restore your property.' },
                { name: 'Flood Cleanup', description: 'Complete flood damage cleanup and restoration after storms, pipe bursts, and appliance malfunctions. We handle everything from water removal to reconstruction.' },
                { name: 'Mold Remediation', description: 'Professional mold removal with containment, air filtration, and antimicrobial treatment. We eliminate mold at the source and prevent future growth.' },
                { name: 'Fire Damage Restoration', description: 'Comprehensive smoke and fire damage cleanup including soot removal, odor elimination, and structural repairs. Insurance claim assistance available.' },
                { name: 'Sewage Cleanup', description: 'Emergency sewage backup cleanup and sanitization. We safely remove hazardous waste and thoroughly disinfect affected areas.' },
            ],
            locations: [
                { city: 'Gilbert', state: 'AZ' },
                { city: 'Mesa', state: 'AZ' },
                { city: 'Chandler', state: 'AZ' },
                { city: 'Tempe', state: 'AZ' },
                { city: 'Queen Creek', state: 'AZ' },
            ],
            colors: { primary: '#1E88E5', secondary: '#1565C0', accent: '#FF9800', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'water damage gilbert az, flood restoration, mold removal, fire damage, emergency restoration, water extraction, sewage cleanup',
            contactEmail: 'info@waterdamagegilbert.com',
            contactPhone: '+14803934707',
            additionalPages: [],
            logoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=200&h=200&fit=crop',
            businessAddress: {
                street: '2338 S Banning St',
                city: 'Gilbert',
                state: 'AZ',
                zip: '85295',
            },
        },
    },
    {
        id: 'plumbing-miami',
        name: 'Miami Plumbing Pro',
        description: 'Full-service plumbing company in South Florida',
        icon: '🔧',
        data: {
            businessName: 'Miami Plumbing Pro',
            industry: 'plumbing',
            customIndustry: '',
            services: [
                { name: 'Emergency Plumbing', description: '24/7 emergency plumbing services for burst pipes, overflows, and urgent repairs.' },
                { name: 'Drain Cleaning', description: 'Professional drain cleaning using hydro-jetting and snake methods.' },
                { name: 'Water Heater Installation', description: 'Tank and tankless water heater installation, repair, and maintenance.' },
                { name: 'Leak Detection', description: 'Advanced leak detection using electronic equipment to find hidden leaks.' },
                { name: 'Sewer Line Repair', description: 'Trenchless sewer repair and replacement services.' },
            ],
            locations: [
                { city: 'Miami', state: 'FL' },
                { city: 'Miami Beach', state: 'FL' },
                { city: 'Coral Gables', state: 'FL' },
                { city: 'Hialeah', state: 'FL' },
            ],
            colors: { primary: '#0066CC', secondary: '#004499', accent: '#FF6B00', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'plumber miami, emergency plumbing, drain cleaning, water heater repair, 24/7 plumber',
            contactEmail: 'service@miamiplumbingpro.com',
            contactPhone: '(305) 555-1234',
            additionalPages: [],
            businessAddress: {
                street: '1250 Brickell Ave, Suite 300',
                city: 'Miami',
                state: 'FL',
                zip: '33131',
            },
        },
    },
    {
        id: 'roofing-dallas',
        name: 'Dallas Roofing Experts',
        description: 'Trusted roofing contractor serving DFW area',
        icon: '🏠',
        data: {
            businessName: 'Dallas Roofing Experts',
            industry: 'roofing',
            customIndustry: '',
            services: [
                { name: 'Roof Replacement', description: 'Complete roof replacement with premium shingles, metal, or tile options.' },
                { name: 'Storm Damage Repair', description: 'Emergency storm and hail damage repair with insurance claim assistance.' },
                { name: 'Roof Inspection', description: 'Comprehensive roof inspections with detailed photo documentation.' },
                { name: 'Gutter Installation', description: 'Seamless gutter installation and gutter guard systems.' },
                { name: 'Commercial Roofing', description: 'Flat roof and TPO roofing for commercial buildings.' },
            ],
            locations: [
                { city: 'Dallas', state: 'TX' },
                { city: 'Fort Worth', state: 'TX' },
                { city: 'Plano', state: 'TX' },
                { city: 'Arlington', state: 'TX' },
                { city: 'Frisco', state: 'TX' },
            ],
            colors: { primary: '#8B4513', secondary: '#654321', accent: '#FFD700', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'roofing dallas, roof repair, storm damage, shingle replacement, roofer near me',
            contactEmail: 'info@dallasroofingexperts.com',
            contactPhone: '(214) 555-7890',
            additionalPages: [],
        },
    },
    {
        id: 'hvac-phoenix',
        name: 'Cool Air Arizona',
        description: 'AC and heating specialists for Phoenix homes',
        icon: '❄️',
        data: {
            businessName: 'Cool Air Arizona',
            industry: 'hvac',
            customIndustry: '',
            services: [
                { name: 'AC Repair', description: 'Fast AC repair service to keep you cool in the Arizona heat.' },
                { name: 'AC Installation', description: 'Energy-efficient air conditioning installation for homes and businesses.' },
                { name: 'Heating Services', description: 'Furnace and heat pump installation, repair, and maintenance.' },
                { name: 'Duct Cleaning', description: 'Professional air duct cleaning to improve indoor air quality.' },
                { name: 'Maintenance Plans', description: 'Preventive maintenance programs to extend HVAC system life.' },
            ],
            locations: [
                { city: 'Phoenix', state: 'AZ' },
                { city: 'Scottsdale', state: 'AZ' },
                { city: 'Tempe', state: 'AZ' },
                { city: 'Mesa', state: 'AZ' },
                { city: 'Chandler', state: 'AZ' },
            ],
            colors: { primary: '#00BFFF', secondary: '#1E90FF', accent: '#FF4500', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'ac repair phoenix, hvac service, air conditioning, heating repair, duct cleaning',
            contactEmail: 'service@coolairarizona.com',
            contactPhone: '(480) 555-2468',
            additionalPages: [],
        },
    },
    {
        id: 'restoration-houston',
        name: 'Houston Water Damage Pros',
        description: 'Water and fire damage restoration specialists',
        icon: '💧',
        data: {
            businessName: 'Houston Water Damage Pros',
            industry: 'restoration',
            customIndustry: '',
            services: [
                { name: 'Water Damage Restoration', description: '24/7 water extraction and drying services for flooded homes.' },
                { name: 'Flood Cleanup', description: 'Complete flood damage cleanup and restoration after storms.' },
                { name: 'Mold Remediation', description: 'Professional mold removal with containment and air scrubbing.' },
                { name: 'Fire Damage Restoration', description: 'Smoke and fire damage cleanup and reconstruction services.' },
                { name: 'Emergency Board-Up', description: 'Emergency property securing and board-up services.' },
            ],
            locations: [
                { city: 'Houston', state: 'TX' },
                { city: 'Katy', state: 'TX' },
                { city: 'Sugar Land', state: 'TX' },
                { city: 'The Woodlands', state: 'TX' },
                { city: 'Pearland', state: 'TX' },
            ],
            colors: { primary: '#1E88E5', secondary: '#1565C0', accent: '#FFC107', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'water damage houston, flood restoration, mold removal, fire damage, emergency restoration',
            contactEmail: 'help@houstonwaterdamagepros.com',
            contactPhone: '(713) 555-9999',
            additionalPages: [],
        },
    },
    {
        id: 'pest-atlanta',
        name: 'Atlanta Pest Shield',
        description: 'Comprehensive pest control for Georgia homes',
        icon: '🐜',
        data: {
            businessName: 'Atlanta Pest Shield',
            industry: 'pest-control',
            customIndustry: '',
            services: [
                { name: 'General Pest Control', description: 'Elimination of ants, roaches, spiders, and common household pests.' },
                { name: 'Termite Treatment', description: 'Termite inspection, treatment, and prevention with warranty.' },
                { name: 'Mosquito Control', description: 'Yard treatment and misting systems to eliminate mosquitoes.' },
                { name: 'Rodent Control', description: 'Humane mouse and rat removal with exclusion services.' },
                { name: 'Bed Bug Treatment', description: 'Heat treatment and chemical options for bed bug elimination.' },
            ],
            locations: [
                { city: 'Atlanta', state: 'GA' },
                { city: 'Marietta', state: 'GA' },
                { city: 'Alpharetta', state: 'GA' },
                { city: 'Roswell', state: 'GA' },
                { city: 'Decatur', state: 'GA' },
            ],
            colors: { primary: '#2E7D32', secondary: '#1B5E20', accent: '#FFA000', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'pest control atlanta, termite treatment, exterminator, bed bugs, mosquito control',
            contactEmail: 'info@atlantapestshield.com',
            contactPhone: '(404) 555-3456',
            additionalPages: [],
        },
    },
    {
        id: 'landscaping-denver',
        name: 'Rocky Mountain Landscapes',
        description: 'Premium landscaping and lawn care in Colorado',
        icon: '🌳',
        data: {
            businessName: 'Rocky Mountain Landscapes',
            industry: 'landscaping',
            customIndustry: '',
            services: [
                { name: 'Landscape Design', description: 'Custom landscape design with 3D visualization and native plants.' },
                { name: 'Lawn Care', description: 'Weekly mowing, fertilization, and weed control programs.' },
                { name: 'Hardscaping', description: 'Patios, walkways, retaining walls, and outdoor living spaces.' },
                { name: 'Tree Service', description: 'Tree trimming, removal, and stump grinding services.' },
                { name: 'Irrigation Systems', description: 'Sprinkler installation, repair, and winterization.' },
            ],
            locations: [
                { city: 'Denver', state: 'CO' },
                { city: 'Aurora', state: 'CO' },
                { city: 'Lakewood', state: 'CO' },
                { city: 'Boulder', state: 'CO' },
                { city: 'Littleton', state: 'CO' },
            ],
            colors: { primary: '#4CAF50', secondary: '#388E3C', accent: '#795548', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'landscaping denver, lawn care, hardscaping, tree service, sprinkler repair',
            contactEmail: 'design@rockymtnlandscapes.com',
            contactPhone: '(303) 555-8765',
            additionalPages: [],
        },
    },
    {
        id: 'electrical-chicago',
        name: 'Windy City Electric',
        description: 'Licensed electricians serving Chicagoland',
        icon: '⚡',
        data: {
            businessName: 'Windy City Electric',
            industry: 'electrical',
            customIndustry: '',
            services: [
                { name: 'Electrical Repair', description: 'Troubleshooting and repair of outlets, switches, and wiring issues.' },
                { name: 'Panel Upgrades', description: 'Electrical panel upgrades to 200 amp service for modern homes.' },
                { name: 'Lighting Installation', description: 'Recessed lighting, outdoor lighting, and smart home systems.' },
                { name: 'EV Charger Installation', description: 'Electric vehicle charger installation for home and business.' },
                { name: 'Commercial Electrical', description: 'Commercial wiring, maintenance, and emergency services.' },
            ],
            locations: [
                { city: 'Chicago', state: 'IL' },
                { city: 'Naperville', state: 'IL' },
                { city: 'Evanston', state: 'IL' },
                { city: 'Oak Park', state: 'IL' },
                { city: 'Schaumburg', state: 'IL' },
            ],
            colors: { primary: '#FFC107', secondary: '#FF9800', accent: '#212121', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'electrician chicago, electrical repair, panel upgrade, EV charger, lighting installation',
            contactEmail: 'service@windycityelectric.com',
            contactPhone: '(312) 555-4321',
            additionalPages: [],
        },
    },
    {
        id: 'cleaning-la',
        name: 'Sparkle Clean LA',
        description: 'Professional house cleaning in Los Angeles',
        icon: '✨',
        data: {
            businessName: 'Sparkle Clean LA',
            industry: 'cleaning',
            customIndustry: '',
            services: [
                { name: 'Regular House Cleaning', description: 'Weekly and bi-weekly cleaning services for busy families.' },
                { name: 'Deep Cleaning', description: 'Thorough top-to-bottom cleaning for spring cleaning or special occasions.' },
                { name: 'Move In/Out Cleaning', description: 'Complete cleaning to help you get your deposit back.' },
                { name: 'Office Cleaning', description: 'Professional commercial cleaning for offices and retail spaces.' },
                { name: 'Post-Construction Cleaning', description: 'Detailed cleanup after renovation or construction projects.' },
            ],
            locations: [
                { city: 'Los Angeles', state: 'CA' },
                { city: 'Santa Monica', state: 'CA' },
                { city: 'Beverly Hills', state: 'CA' },
                { city: 'Pasadena', state: 'CA' },
                { city: 'Glendale', state: 'CA' },
            ],
            colors: { primary: '#9C27B0', secondary: '#7B1FA2', accent: '#00BCD4', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'house cleaning los angeles, maid service, deep cleaning, move out cleaning, office cleaning',
            contactEmail: 'book@sparklecleanla.com',
            contactPhone: '(310) 555-6543',
            additionalPages: [],
        },
    },
    {
        id: 'garage-seattle',
        name: 'Seattle Garage Door Pros',
        description: 'Garage door repair and installation experts',
        icon: '🚗',
        data: {
            businessName: 'Seattle Garage Door Pros',
            industry: 'garage-door',
            customIndustry: '',
            services: [
                { name: 'Garage Door Repair', description: 'Same-day repair for springs, cables, openers, and panels.' },
                { name: 'New Door Installation', description: 'Beautiful new garage doors in steel, wood, and carriage styles.' },
                { name: 'Opener Installation', description: 'Smart garage door openers with WiFi and battery backup.' },
                { name: 'Spring Replacement', description: 'Safe torsion and extension spring replacement.' },
                { name: 'Maintenance', description: 'Annual maintenance to extend the life of your garage door.' },
            ],
            locations: [
                { city: 'Seattle', state: 'WA' },
                { city: 'Bellevue', state: 'WA' },
                { city: 'Tacoma', state: 'WA' },
                { city: 'Redmond', state: 'WA' },
                { city: 'Kirkland', state: 'WA' },
            ],
            colors: { primary: '#607D8B', secondary: '#455A64', accent: '#FF5722', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'garage door repair seattle, garage door installation, spring replacement, opener repair',
            contactEmail: 'service@seattlegaragedoorpros.com',
            contactPhone: '(206) 555-7654',
            additionalPages: [],
        },
    },
    {
        id: 'solar-vegas',
        name: 'Vegas Solar Solutions',
        description: 'Solar panel installation for Nevada homes',
        icon: '☀️',
        data: {
            businessName: 'Vegas Solar Solutions',
            industry: 'solar-panel',
            customIndustry: '',
            services: [
                { name: 'Residential Solar', description: 'Custom solar panel systems designed for maximum energy savings.' },
                { name: 'Commercial Solar', description: 'Large-scale solar installations for businesses and properties.' },
                { name: 'Battery Storage', description: 'Tesla Powerwall and backup battery installation.' },
                { name: 'Solar Maintenance', description: 'Panel cleaning, monitoring, and maintenance services.' },
                { name: 'Solar Financing', description: 'Help with financing options, tax credits, and rebates.' },
            ],
            locations: [
                { city: 'Las Vegas', state: 'NV' },
                { city: 'Henderson', state: 'NV' },
                { city: 'North Las Vegas', state: 'NV' },
                { city: 'Boulder City', state: 'NV' },
                { city: 'Summerlin', state: 'NV' },
            ],
            colors: { primary: '#FF9800', secondary: '#F57C00', accent: '#2196F3', background: '#ffffff', text: '#1f2937' },
            goal: 'leads',
            keywords: 'solar panels las vegas, solar installation, battery storage, renewable energy, solar financing',
            contactEmail: 'info@vegassolarsolutions.com',
            contactPhone: '(702) 555-8888',
            additionalPages: [],
        },
    },
];

// Get a sample by ID
export function getSampleById(id: string): SampleBusiness | undefined {
    return SAMPLE_BUSINESSES.find(sample => sample.id === id);
}
