// SEO Files Generator - sitemap.xml, robots.txt, llms.txt

import { Website, Page } from '../types';

// Generate sitemap.xml content
export function generateSitemap(website: Website, baseUrl: string): string {
    const now = new Date().toISOString().split('T')[0];

    // Get all pages with priorities
    const pages = website.pages.map(page => ({
        url: page.slug ? `${baseUrl}/${page.slug}` : baseUrl,
        lastmod: now,
        changefreq: getChangeFreq(page.type),
        priority: getPriority(page.type),
    }));

    // Add blog posts
    const blogPosts = website.blogPosts
        .filter(post => post.status === 'published')
        .map(post => ({
            url: `${baseUrl}/blog/${post.slug}`,
            lastmod: post.updatedAt.split('T')[0],
            changefreq: 'weekly',
            priority: '0.6',
        }));

    const allUrls = [...pages, ...blogPosts];

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${allUrls.map(url => `  <url>
    <loc>${url.url}</loc>
    <lastmod>${url.lastmod}</lastmod>
    <changefreq>${url.changefreq}</changefreq>
    <priority>${url.priority}</priority>
  </url>`).join('\n')}
</urlset>`;
}

// Generate robots.txt content
export function generateRobotsTxt(baseUrl: string): string {
    return `# robots.txt for ${baseUrl}
# Generated by AI Website Builder

User-agent: *
Allow: /

# Sitemap
Sitemap: ${baseUrl}/sitemap.xml

# Crawl-delay
Crawl-delay: 1

# Disallow admin/internal pages
Disallow: /api/
Disallow: /_next/
Disallow: /admin/

# Allow all important content
Allow: /services/
Allow: /locations/
Allow: /blog/
Allow: /about
Allow: /contact
`;
}

// Generate llms.txt content (AI-friendly summary for LLMs)
export function generateLlmsTxt(website: Website, baseUrl: string): string {
    const services = website.services.map(s => s.name).join(', ');
    const locations = website.locations.map(l => l.city).join(', ');

    return `# ${website.businessName}
> ${website.seoSettings.siteDescription}

## About
${website.businessName} is a professional ${website.industry} company serving ${locations || 'local areas'}. We provide high-quality services including ${services || 'various services'}.

## Services
${website.services.map(s => `- ${s.name}: ${s.description}`).join('\n')}

## Service Areas
${website.locations.map(l => `- ${l.city}${l.state ? `, ${l.state}` : ''}`).join('\n')}

## Contact
- Website: ${baseUrl}
- Phone: ${website.contactPhone || 'Contact us'}
- Email: ${website.contactEmail || 'Contact us'}

## Pages
${website.pages.map(p => `- [${p.title}](${baseUrl}/${p.slug || ''})`).join('\n')}

## Recent Blog Posts
${website.blogPosts.filter(p => p.status === 'published').slice(0, 5).map(p => `- [${p.title}](${baseUrl}/blog/${p.slug})`).join('\n') || 'No blog posts yet.'}

---
This business website was created with AI Website Builder.
`;
}

// Generate HTML sitemap page content
export function generateHtmlSitemap(website: Website, baseUrl: string): string {
    return `
    <section class="sitemap-page">
      <div class="container">
        <h1>Sitemap</h1>
        <p>Browse all pages on our website:</p>
        
        <div class="sitemap-columns">
          <div class="sitemap-section">
            <h2>Main Pages</h2>
            <ul>
              ${website.pages.filter(p => ['home', 'about', 'contact', 'services', 'blog'].includes(p.type)).map(page => `
                <li><a href="/${page.slug || ''}">${page.title}</a></li>
              `).join('')}
            </ul>
          </div>
          
          <div class="sitemap-section">
            <h2>Services</h2>
            <ul>
              ${website.services.map(service => `
                <li><a href="/services/${service.slug}">${service.name}</a></li>
              `).join('')}
            </ul>
          </div>
          
          <div class="sitemap-section">
            <h2>Service Areas</h2>
            <ul>
              ${website.locations.map(location => `
                <li><a href="/locations/${location.slug}">${location.city}${location.state ? `, ${location.state}` : ''}</a></li>
              `).join('')}
            </ul>
          </div>
          
          <div class="sitemap-section">
            <h2>Blog</h2>
            <ul>
              ${website.blogPosts.filter(p => p.status === 'published').map(post => `
                <li><a href="/blog/${post.slug}">${post.title}</a></li>
              `).join('')}
              ${website.blogPosts.length === 0 ? '<li>No blog posts yet</li>' : ''}
            </ul>
          </div>
          
          <div class="sitemap-section">
            <h2>Legal</h2>
            <ul>
              <li><a href="/privacy-policy">Privacy Policy</a></li>
              <li><a href="/terms-of-service">Terms of Service</a></li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  `;
}

// Generate Privacy Policy content
export function generatePrivacyPolicy(website: Website): string {
    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    return `
    <section class="legal-page">
      <div class="container">
        <h1>Privacy Policy</h1>
        <p class="legal-date">Last Updated: ${now}</p>
        
        <div class="legal-content">
          <h2>Introduction</h2>
          <p>${website.businessName} ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website or use our services.</p>
          
          <h2>Information We Collect</h2>
          <h3>Personal Information</h3>
          <p>We may collect personal information that you voluntarily provide to us when you:</p>
          <ul>
            <li>Fill out a contact form</li>
            <li>Request a quote or estimate</li>
            <li>Subscribe to our newsletter</li>
            <li>Contact us via phone or email</li>
          </ul>
          <p>This information may include:</p>
          <ul>
            <li>Name</li>
            <li>Email address</li>
            <li>Phone number</li>
            <li>Address</li>
            <li>Service inquiry details</li>
          </ul>
          
          <h3>Automatically Collected Information</h3>
          <p>When you visit our website, we may automatically collect certain information about your device, including:</p>
          <ul>
            <li>IP address</li>
            <li>Browser type</li>
            <li>Operating system</li>
            <li>Access times</li>
            <li>Pages viewed</li>
            <li>Referring website</li>
          </ul>
          
          <h2>How We Use Your Information</h2>
          <p>We use the information we collect to:</p>
          <ul>
            <li>Provide, operate, and maintain our services</li>
            <li>Respond to your inquiries and requests</li>
            <li>Send you service-related communications</li>
            <li>Improve our website and services</li>
            <li>Comply with legal obligations</li>
          </ul>
          
          <h2>Information Sharing</h2>
          <p>We do not sell, trade, or rent your personal information to third parties. We may share information with:</p>
          <ul>
            <li>Service providers who assist our operations</li>
            <li>Legal authorities when required by law</li>
            <li>Business partners with your consent</li>
          </ul>
          
          <h2>Data Security</h2>
          <p>We implement appropriate technical and organizational measures to protect your personal information. However, no method of transmission over the internet is 100% secure.</p>
          
          <h2>Your Rights</h2>
          <p>Depending on your location, you may have rights regarding your personal information, including:</p>
          <ul>
            <li>Access to your personal data</li>
            <li>Correction of inaccurate data</li>
            <li>Deletion of your data</li>
            <li>Opt-out of marketing communications</li>
          </ul>
          
          <h2>Cookies</h2>
          <p>Our website may use cookies to enhance your experience. You can set your browser to refuse cookies, but this may limit some functionality.</p>
          
          <h2>Third-Party Links</h2>
          <p>Our website may contain links to third-party websites. We are not responsible for the privacy practices of these external sites.</p>
          
          <h2>Children's Privacy</h2>
          <p>Our services are not directed to individuals under 18. We do not knowingly collect information from children.</p>
          
          <h2>Changes to This Policy</h2>
          <p>We may update this Privacy Policy periodically. Changes will be posted on this page with an updated revision date.</p>
          
          <h2>Contact Us</h2>
          <p>If you have questions about this Privacy Policy, please contact us:</p>
          <ul>
            <li>Phone: ${website.contactPhone || 'Contact us'}</li>
            <li>Email: ${website.contactEmail || 'Contact us'}</li>
          </ul>
        </div>
      </div>
    </section>
  `;
}

// Generate Terms of Service content
export function generateTermsOfService(website: Website): string {
    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    return `
    <section class="legal-page">
      <div class="container">
        <h1>Terms of Service</h1>
        <p class="legal-date">Last Updated: ${now}</p>
        
        <div class="legal-content">
          <h2>Agreement to Terms</h2>
          <p>By accessing or using the services of ${website.businessName} ("Company," "we," "us," or "our"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.</p>
          
          <h2>Services</h2>
          <p>${website.businessName} provides professional ${website.industry} services. The specific services, pricing, and terms will be detailed in individual service agreements or quotes provided to you.</p>
          
          <h2>Estimates and Pricing</h2>
          <ul>
            <li>All estimates are provided in good faith based on the information available at the time of assessment.</li>
            <li>Final pricing may vary if additional work is discovered or requested.</li>
            <li>We will communicate any pricing changes before proceeding with additional work.</li>
            <li>Payment terms will be specified in your service agreement or invoice.</li>
          </ul>
          
          <h2>Scheduling and Cancellations</h2>
          <ul>
            <li>We will make reasonable efforts to accommodate your preferred scheduling.</li>
            <li>Emergency services may be subject to additional fees.</li>
            <li>Cancellations should be made at least 24 hours in advance when possible.</li>
            <li>Late cancellations or no-shows may result in a cancellation fee.</li>
          </ul>
          
          <h2>Warranties and Guarantees</h2>
          <p>We stand behind our work and offer warranties on our services. Specific warranty terms will be provided with your service agreement. Warranties typically cover:</p>
          <ul>
            <li>Workmanship defects</li>
            <li>Materials (subject to manufacturer warranties)</li>
            <li>Satisfaction guarantee for initial service</li>
          </ul>
          
          <h2>Limitation of Liability</h2>
          <p>To the maximum extent permitted by law:</p>
          <ul>
            <li>Our liability is limited to the amount paid for the specific service in question.</li>
            <li>We are not liable for indirect, incidental, or consequential damages.</li>
            <li>We are not responsible for pre-existing conditions not caused by our work.</li>
          </ul>
          
          <h2>Customer Responsibilities</h2>
          <p>By using our services, you agree to:</p>
          <ul>
            <li>Provide accurate information about the work needed</li>
            <li>Ensure safe access to the work area</li>
            <li>Disclose any known hazards or issues</li>
            <li>Make timely payments as agreed</li>
            <li>Communicate any concerns promptly</li>
          </ul>
          
          <h2>Insurance</h2>
          <p>${website.businessName} maintains appropriate insurance coverage including general liability and workers' compensation. Certificates of insurance are available upon request.</p>
          
          <h2>Intellectual Property</h2>
          <p>All content on this website, including text, images, and design, is the property of ${website.businessName} and is protected by copyright law.</p>
          
          <h2>Dispute Resolution</h2>
          <p>Any disputes arising from these terms or our services will be resolved through good-faith negotiation. If necessary, disputes may be submitted to binding arbitration in accordance with applicable laws.</p>
          
          <h2>Changes to Terms</h2>
          <p>We reserve the right to modify these terms at any time. Continued use of our services after changes indicates acceptance of the new terms.</p>
          
          <h2>Contact Information</h2>
          <p>For questions about these Terms of Service, please contact us:</p>
          <ul>
            <li>Phone: ${website.contactPhone || 'Contact us'}</li>
            <li>Email: ${website.contactEmail || 'Contact us'}</li>
          </ul>
        </div>
      </div>
    </section>
  `;
}

// Helper functions
function getChangeFreq(pageType: string): string {
    switch (pageType) {
        case 'home': return 'weekly';
        case 'blog': return 'daily';
        case 'services': return 'monthly';
        case 'contact': return 'monthly';
        default: return 'monthly';
    }
}

function getPriority(pageType: string): string {
    switch (pageType) {
        case 'home': return '1.0';
        case 'services': return '0.9';
        case 'service-single': return '0.8';
        case 'location': return '0.8';
        case 'about': return '0.7';
        case 'contact': return '0.7';
        case 'blog': return '0.6';
        default: return '0.5';
    }
}
