// SEO Files Generator
// Generates robots.txt and sitemap.xml with dynamic domain detection

import { Website, Page, BlogPost, Service } from '../types';

/**
 * Generate robots.txt content
 * Uses placeholder for sitemap URL - frontend will replace with actual origin
 */
export function generateRobotsTxt(): string {
  return `# Robots.txt - Generated by SMBify Rank
# All pages are allowed for indexing

User-agent: *
Allow: /

# Sitemap
Sitemap: {{SITE_ORIGIN}}/sitemap.xml
`;
}

/**
 * Generate sitemap.xml content
 * All URLs use placeholder that frontend replaces with actual domain
 */
export function generateSitemapXml(website: Website): string {
  const now = new Date().toISOString().split('T')[0];
  const pages: Array<{ url: string; priority: string; changefreq: string }> = [];

  // Homepage
  pages.push({
    url: '/',
    priority: '1.0',
    changefreq: 'weekly'
  });

  // Main pages
  website.pages.forEach(page => {
    if (page.type === 'home') return; // Already added homepage
    pages.push({
      url: `/${page.slug}`,
      priority: getPagePriority(page.type),
      changefreq: 'monthly'
    });
  });

  // Service pages
  website.services.forEach(service => {
    pages.push({
      url: `/services/${service.slug}`,
      priority: '0.8',
      changefreq: 'monthly'
    });
  });

  // Location pages
  website.locations.forEach(location => {
    pages.push({
      url: `/locations/${location.slug}`,
      priority: '0.7',
      changefreq: 'monthly'
    });
  });

  // Blog posts
  if (website.blogPosts) {
    // Blog index
    pages.push({
      url: '/blog',
      priority: '0.8',
      changefreq: 'weekly'
    });

    // Individual blog posts
    website.blogPosts
      .filter(post => post.status === 'published')
      .forEach(post => {
        pages.push({
          url: `/blog/${post.slug}`,
          priority: '0.6',
          changefreq: 'monthly'
        });
      });
  }

  // Legal pages
  pages.push(
    { url: '/privacy-policy', priority: '0.3', changefreq: 'yearly' },
    { url: '/terms-of-service', priority: '0.3', changefreq: 'yearly' }
  );

  // Generate XML
  const urlEntries = pages.map(page => `
  <url>
    <loc>{{SITE_ORIGIN}}${page.url}</loc>
    <lastmod>${now}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
  </url>`).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9
        http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd">
${urlEntries}
</urlset>`;
}

/**
 * Get priority based on page type
 */
function getPagePriority(type: string): string {
  switch (type) {
    case 'home': return '1.0';
    case 'services': return '0.9';
    case 'about': return '0.7';
    case 'contact': return '0.8';
    case 'locations': return '0.7';
    case 'blog': return '0.8';
    default: return '0.5';
  }
}

/**
 * Generate HTML sitemap page for users
 */
export function generateHtmlSitemap(website: Website): string {
  const serviceLinks = website.services
    .map(s => `<li><a href="/services/${s.slug}">${s.name}</a></li>`)
    .join('\n');

  const locationLinks = website.locations
    .map(l => `<li><a href="/locations/${l.slug}">${l.city}${l.state ? `, ${l.state}` : ''}</a></li>`)
    .join('\n');

  const blogLinks = (website.blogPosts || [])
    .filter(p => p.status === 'published')
    .map(p => `<li><a href="/blog/${p.slug}">${p.title}</a></li>`)
    .join('\n');

  return `
    <section class="sitemap-section" style="padding: 80px 0;">
        <div class="container">
            <h1 style="margin-bottom: 40px; font-size: 2.5rem;">Sitemap</h1>
            
            <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(250px, 1fr)); gap: 40px;">
                <div>
                    <h2 style="margin-bottom: 15px; font-size: 1.25rem; color: var(--primary);">Main Pages</h2>
                    <ul style="list-style: none;">
                        <li><a href="/">Home</a></li>
                        <li><a href="/about">About Us</a></li>
                        <li><a href="/services">Services</a></li>
                        <li><a href="/contact">Contact</a></li>
                        <li><a href="/blog">Blog</a></li>
                    </ul>
                </div>
                
                ${serviceLinks ? `
                <div>
                    <h2 style="margin-bottom: 15px; font-size: 1.25rem; color: var(--primary);">Our Services</h2>
                    <ul style="list-style: none;">
                        ${serviceLinks}
                    </ul>
                </div>
                ` : ''}
                
                ${locationLinks ? `
                <div>
                    <h2 style="margin-bottom: 15px; font-size: 1.25rem; color: var(--primary);">Service Areas</h2>
                    <ul style="list-style: none;">
                        ${locationLinks}
                    </ul>
                </div>
                ` : ''}
                
                ${blogLinks ? `
                <div>
                    <h2 style="margin-bottom: 15px; font-size: 1.25rem; color: var(--primary);">Blog Posts</h2>
                    <ul style="list-style: none;">
                        ${blogLinks}
                    </ul>
                </div>
                ` : ''}
                
                <div>
                    <h2 style="margin-bottom: 15px; font-size: 1.25rem; color: var(--primary);">Legal</h2>
                    <ul style="list-style: none;">
                        <li><a href="/privacy-policy">Privacy Policy</a></li>
                        <li><a href="/terms-of-service">Terms of Service</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    `;
}

/**
 * Process robots.txt/sitemap with actual domain
 * Call this function with the actual site origin at runtime
 */
export function processWithOrigin(content: string, origin: string): string {
  // Remove trailing slash if present
  const cleanOrigin = origin.replace(/\/$/, '');
  return content.replace(/\{\{SITE_ORIGIN\}\}/g, cleanOrigin);
}

/**
 * Validate SEO readiness
 */
export function validateSeoReadiness(website: Website): { ready: boolean; issues: string[] } {
  const issues: string[] = [];

  // Check for pages
  if (!website.pages || website.pages.length === 0) {
    issues.push('No pages found');
  }

  // Check for meta descriptions
  website.pages.forEach(page => {
    if (!page.seo?.description) {
      issues.push(`Missing meta description on: ${page.title || page.slug}`);
    }
    if (!page.seo?.title) {
      issues.push(`Missing SEO title on: ${page.title || page.slug}`);
    }
  });

  // Check for business info
  if (!website.businessName) {
    issues.push('Missing business name');
  }

  return {
    ready: issues.length === 0,
    issues
  };
}
